cnf_secret_key: blabla

cnf_token_type: header

cnf_token_name: x-token

cnf_token_algorithm: HS256

cnf_authentication_url:

cnf_user_param_name: user

cnf_pw_param_name: password

auth_user_entity:

auth_user_specification:

auth_public_resources:

auth_enabled: false

default_page_size: 20

page_size_param_name: pageSize

page_param_name: page