- git:
    repo: https://github.com/swagger-api/swagger-ui.git
    dest: /tmp/swagger-ui
    force: yes
    version: HEAD

- file:
    path: /tmp/swagger-ui/dist
    mode: 0777

- name: remove if already exists
  command: rm -rf /usr/share/nginx/html/swagger

- name: move swagger-uid dist to nginx html
  command: mv -f /tmp/swagger-ui/dist /usr/share/nginx/html/swagger

- file:
    src: /etc/nginx/sites-available/swagger-ui
    dest: /etc/nginx/sites-enabled/swagger-ui
    state: link

