<?php
/**
 * Created by PhpStorm.
 * User: michaelhunger
 * Date: 03/04/17
 * Time: 20:20
 */

namespace taurus\tests\db\query;


use taurus\framework\config\TaurusContainerConfig;
use taurus\framework\Container;
use taurus\framework\db\query\SpecificationBuilder;
use taurus\framework\mock\MockRequest;
use taurus\framework\routing\Request;
use taurus\tests\AbstractTaurusTest;
use taurus\tests\fixtures\TestSpecification;

class SpecificationBuilderTest extends AbstractTaurusTest
{
    /** @var SpecificationBuilder */
    private $specBuilder;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->specBuilder = Container::getInstance()->getService(TaurusContainerConfig::SERVICE_SPECIFICATION_BUILDER);
    }

    public function testBuildSpecification()
    {
        $expectedSpecification = new TestSpecification('test', 1, 'mytest');

        /** @var MockRequest $mockRequest */
        $mockRequest = Container::getInstance()->getService(TaurusContainerConfig::SERVICE_MOCK_REQUEST);
        $mockRequest->setRequestVariables([
            'spec1' => 'test',
            'spec2' => 1,
            'spec3' => 'mytest'
        ])->setMethod(Request::HTTP_GET);

        $actualResult = $this->specBuilder->build($mockRequest, TestSpecification::class);

        $this->assertEquals(
            $expectedSpecification,
            $actualResult,
            'Did not create specification correctly'
        );

    }

}