<?php
/**
 * Created by PhpStorm.
 * User: michaelhunger
 * Date: 20/02/17
 * Time: 22:16
 */

namespace taurus\tests\routing;


use fitnessmanager\exercise\Exercise;
use taurus\framework\api\GetByIdApiController;
use taurus\framework\api\GetEntityByIdDefaultServiceImpl;
use taurus\framework\config\TaurusContainerConfig;
use taurus\framework\Container;

use taurus\framework\routing\RouteConfig;
use taurus\tests\AbstractTaurusTest;

class RouteConfigTest extends AbstractTaurusTest
{
    /** @var RouteConfig */
    private $subject;

    public function setUp()
    {
        $this->subject = Container::getInstance()->getService(TaurusContainerConfig::SERVICE_ROUTE_CONFIG);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testRouteConfigDefaultGetByIdRouteOnlyEntity()
    {
        /** @var GetByIdApiController $expectedController */
        $expectedController = Container::getInstance()->getService(TaurusContainerConfig::SERVICE_DEFAULT_GETBYID_CONTROLLER);
        /** @var GetEntityByIdDefaultServiceImpl $service */
        $service = Container::getInstance()->getService(TaurusContainerConfig::SERVICE_DEFAULT_GETBYID_SERVICE);
        $service->setEntityClass(Exercise::class);

        $expectedController->setGetEntityByIdService($service);
        $expectedController->setIdParamName('id');


        $actualController = $this->subject->getRoute('GET', 'exercise');

        $this->assertEquals(
            $expectedController,
            $actualController
        );
    }
}
