<?php
/**
 * Created by PhpStorm.
 * User: michaelhunger
 * Date: 18/06/17
 * Time: 14:18
 */

namespace fitnessmanager\tests;


use fitnessmanager\config\FitnessManagerTestConfig;
use taurus\framework\config\TaurusContainerConfig;
use taurus\framework\Container;
use taurus\tests\AbstractDatabaseTest;

abstract class AbstractFitnessManagerDatabaseTest extends AbstractDatabaseTest
{
    public function setUp()
    {
        $this->dbname = 'fitnessmanager_test';
        $this->dbuser = 'fitness';
        $this->dbpw= 'fitness';
        $this->dbhost = 'localhost';

        $this->fixturesDbState = '/fixtures/db/';

        $this->fixturesJsonResults = '/fixtures/jsonResults/';

        $config = (new TaurusContainerConfig())
            ->merge(new FitnessManagerTestConfig())
        ->merge(new FitnessManagerTestConfig());
        Container::getInstance()->setContainerConfig($config);

        parent::setUp(); // TODO: Change the autogenerated stub

    }
}
