---
- hosts: all
  sudo: true
  vars:
    web_server: nginxphp
    servername: dev-taurus.com 192.168.44.14
    timezone: UTC
  vars_files:
    - vars/mysql.yml
    - vars/common.yml
    - [ "vars/nginxphp.yml", "vars/ws_defaults.yml" ]
  roles:
    - init
    - php5-cli
    - nginx
    - php5-fpm
    - mysql
    - phpcommon
    - php-pecl
    - app
