<?php
/**
 * Created by PhpStorm.
 * User: michaelhunger
 * Date: 24/02/17
 * Time: 20:14
 */

namespace taurus\tests\api;


use fitnessmanager\exercise\Exercise;
use fitnessmanager\exercise\ExerciseGroup;
use fitnessmanager\exercise\MuscleGroup;
use fitnessmanager\workout\WorkoutLocation;
use taurus\framework\api\GetAllEntitiesDefaultServiceImpl;
use taurus\framework\config\TaurusContainerConfig;
use taurus\framework\Container;
use taurus\tests\AbstractDatabaseTest;

class GetAllEntitiesDefaultServiceImplTest extends AbstractDatabaseTest
{
    /** @var GetAllEntitiesDefaultServiceImpl */
    private $service;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        /** @var GetAllEntitiesDefaultServiceImpl $service */
        $service = Container::getInstance()->getService(TaurusContainerConfig::SERVICE_DEFAULT_GET_ALL_ENTITIES_SERVICE);
        $service->setEntityClass(Exercise::class);
        $this->service = $service;
    }

    /**
     * @return array
     */
    function getFixtureFiles(): array
    {
        return [
            'workout_location.xml',
            'muscle_group.xml',
            'exercise_group.xml',
            'exercise.xml'
        ];
    }

    public function testGetAllEntities()
    {
        $expectedResult = [
            (new Exercise())->setId(3)->setName('Pull-Up')->setDifficulty('hard')->setVariantName('Chinup')
                ->setWorkoutLocation(
                    (new WorkoutLocation())->setId(1)->setName('TUM Sportzentrum')
                )->setExerciseGroup(
                    (new ExerciseGroup())->setId(1)->setName('Pullups')->setDifficulty('hard')
                        ->setMuscleGroup(
                            (new MuscleGroup())->setId(5)->setName('Back')
                        )
                ),
            (new Exercise())->setId(4)->setName('Push-Ups')->setDifficulty('medium')->setVariantName('Standing')
                ->setWorkoutLocation(
                    (new WorkoutLocation())->setId(1)->setName('TUM Sportzentrum')
                )->setExerciseGroup(
                    (new ExerciseGroup())->setId(2)->setName('Pushups')->setDifficulty('medium')
                        ->setMuscleGroup(
                            (new MuscleGroup())->setId(1)->setName('Chest')
                        )
                )
        ];

        $this->assertEquals(
            $expectedResult,
            $this->service->getAllEntities(),
            'Could not load all entities in api default service implementation'
        );

    }
}
