<?php
/**
 * Created by PhpStorm.
 * User: michaelhunger
 * Date: 24/02/17
 * Time: 20:14
 */

namespace taurus\tests\api;


use fitnessmanager\exercise\Exercise;
use taurus\framework\api\GetAllEntitiesDefaultServiceImpl;
use taurus\framework\config\TaurusContainerConfig;
use taurus\framework\Container;
use taurus\tests\AbstractDatabaseTest;

class GetAllEntitiesDefaultServiceImplTest extends AbstractDatabaseTest
{
    /** @var GetAllEntitiesDefaultServiceImpl */
    private $service;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        /** @var GetAllEntitiesDefaultServiceImpl $service */
        $service = Container::getInstance()->getService(TaurusContainerConfig::SERVICE_DEFAULT_GET_ALL_ENTITIES_SERVICE);
        $service->setEntityClass(Exercise::class);
        $this->service = $service;
    }

    /**
     * @return array
     */
    function getFixtureFiles(): array
    {
        return [
            'exercise.xml'
        ];
    }

    public function testGetAllEntities()
    {
        $expectedResult = [
            (new Exercise())->setId(3)->setName('Pull-Up')->setDifficulty('hard')->setVariantName('Chinup'),
            (new Exercise())->setId(4)->setName('Push-Ups')->setDifficulty('medium')->setVariantName('Standing')
        ];

        $this->assertEquals(
            $expectedResult,
            $this->service->getAllEntities(),
            'Could not load all entities in api default service implementation'
        );

    }
}
