<?php
/**
 * Created by PhpStorm.
 * User: michaelhunger
 * Date: 03/04/17
 * Time: 20:42
 */

namespace taurus\tests\api;


use taurus\framework\config\TaurusContainerConfig;
use taurus\framework\Container;
use taurus\framework\mock\MockServer;
use taurus\tests\AbstractTaurusDatabaseTest;

class GetBySpecificationApiControllerTest extends AbstractTaurusDatabaseTest
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    function getFixtureFiles(): array
    {
        return [
            'workout_location.xml',
            'muscle_group.xml',
            'exercise_group.xml',
            'exercise.xml'
        ];
    }

    public function testGetBySpecificationController()
    {
        /** @var MockServer $mockServer */
        $mockServer = Container::getInstance()
            ->getService(TaurusContainerConfig::SERVICE_MOCK_SERVER);

        $actualResponse = $mockServer->get(
            '/api/exercisesByDateAndLocation',
            'GET',
            [
                'name' => 'Push-Ups',
                'difficulty' => 'medium'
            ]
        );

        $this->compareResultToFixture(
            $actualResponse,
            __FUNCTION__,
            'Could not get all resources for exercises through the standard api controller'
        );

    }
}
