<?php
/**
 * Created by PhpStorm.
 * User: michaelhunger
 * Date: 20/02/17
 * Time: 22:49
 */

namespace taurus\tests\api;


use fitnessmanager\exercise\Exercise;
use taurus\framework\api\GetByIdApiController;
use taurus\framework\api\GetEntityByIdDefaultServiceImpl;
use taurus\framework\config\TaurusContainerConfig;
use taurus\framework\Container;
use taurus\framework\mock\MockRequest;
use taurus\tests\AbstractDatabaseTest;

class GetByIdApiControllerTest extends AbstractDatabaseTest
{
    /** @var GetByIdApiController */
    private $controller;

    /**
     * @return array
     */
    function getFixtureFiles(): array
    {
        return [
            'exercise.xml'
        ];
    }

    public function setUp()
    {
        /** @var GetByIdApiController $controller */
        $controller = Container::getInstance()->getService(TaurusContainerConfig::SERVICE_DEFAULT_GETBYID_CONTROLLER);
        /** @var GetEntityByIdDefaultServiceImpl $service */
        $service = Container::getInstance()->getService(TaurusContainerConfig::SERVICE_DEFAULT_GETBYID_SERVICE);
        $service->setEntityClass(Exercise::class);

        $controller->setGetEntityByIdService($service);
        $controller->setIdParamName('id');
        $this->controller = $controller;

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testControllerGetId()
    {
        $request = new MockRequest();
        $request->setMethod('GET');
        $request->setUrl('/exercise');
        $request->setRequestVariables([
            'id' => 3
        ]);

        $actualResult = $this->controller->handleRequest($request);
        $expectedResult = (new Exercise())->setId(3)->setDifficulty('hard')->setName('Pull-Up')->setVariantName('Chinup');

        $this->assertEquals(
            $expectedResult,
            $actualResult,
            'Could not get the item by id'
        );
    }

}
