<?php
/**
 * Created by PhpStorm.
 * User: michaelhunger
 * Date: 20/02/17
 * Time: 22:36
 */

namespace taurus\tests\api;


use fitnessmanager\exercise\Exercise;
use taurus\framework\api\GetEntityByIdDefaultServiceImpl;
use taurus\framework\config\TaurusContainerConfig;
use taurus\framework\Container;
use taurus\tests\AbstractDatabaseTest;

class GetEntityByIdDefaultImplTest extends AbstractDatabaseTest
{
    /** @var GetEntityByIdDefaultServiceImpl */
    private $getEntityByIdService;

    public function setUp()
    {
        $this->getEntityByIdService = Container::getInstance()->getService(TaurusContainerConfig::SERVICE_DEFAULT_GETBYID_SERVICE);
        $this->getEntityByIdService->setEntityClass(Exercise::class);

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @return array
     */
    function getFixtureFiles(): array
    {
        return [
            'exercise.xml'
        ];
    }

    public function testGetEntityByIdDefaultServiceTest()
    {
        $actualResult = $this->getEntityByIdService->getEntityById(3);
        $expectedResult = (new Exercise())->setId(3)->setDifficulty('hard')->setName('Pull-Up')->setVariantName('Chinup');

        $this->assertEquals(
            $expectedResult,
            $actualResult,
            'The two entities are not the same'
        );
    }
}