<?php
/**
 * Created by PhpStorm.
 * User: michaelhunger
 * Date: 22/02/17
 * Time: 20:39
 */

namespace taurus\tests\api;


use fitnessmanager\exercise\Exercise;
use taurus\framework\api\SaveEntityController;
use taurus\framework\api\SaveEntityDefaultServiceImpl;
use taurus\framework\config\TaurusContainerConfig;
use taurus\framework\Container;
use taurus\framework\db\entity\BaseRepository;
use taurus\framework\http\Controller;
use taurus\framework\mock\MockRequest;
use taurus\tests\AbstractDatabaseTest;

class SaveEntityControllerTest extends AbstractDatabaseTest
{
    /** @var SaveEntityController */
    private $controller;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        /** @var SaveEntityController $controller */
        $controller = Container::getInstance()->getService(TaurusContainerConfig::SERVICE_DEFAULT_SAVE_ENTITY_CONTROLLER);
        /** @var SaveEntityDefaultServiceImpl $service */
        $service = Container::getInstance()->getService(TaurusContainerConfig::SERVICE_DEFAULT_SAVE_ENTITY_SERVICE);
        $service->setEntityClass(Exercise::class);
        $controller->setService($service);
        $this->controller = $controller;
    }

    /**
     * @return array
     */
    function getFixtureFiles(): array
    {
        return [
            'exercise.xml'
        ];
    }

    public function testDefaultSaveEntityController()
    {
        $mockRequest = (new MockRequest())
            ->setMethod('POST')
            ->setUrl('/exercise')
            ->setRequestVariables([
                'exercise' => [
                    'name' => 'TestExercise',
                    'difficulty' => 'TestDifficulty',
                    'variant_name' => 'TestVariant'
                ]
            ]);

        $this->controller->handleRequest($mockRequest);

        $expectedEntity = (new Exercise())->setId(5)
            ->setName('TestExercise')
            ->setDifficulty('TestDifficulty')
            ->setVariantName('TestVariant');

        /** @var BaseRepository $baserepo */
        $baserepo = Container::getInstance()->getService(TaurusContainerConfig::SERVICE_BASE_REPOSITORY);
        $actualEntity = $baserepo->findOne(5, Exercise::class);

        $this->assertEquals(
            $expectedEntity,
            $actualEntity,
            'Could not store exercise entity correctly in save Default entity controller'
        );
    }
}
