<?php
/**
 * Created by PhpStorm.
 * User: michaelhunger
 * Date: 22/02/17
 * Time: 20:39
 */

namespace taurus\tests\api;


use taurus\tests\testmodel\Exercise;
use taurus\tests\testmodel\ExerciseGroup;
use taurus\tests\testmodel\MuscleGroup;
use taurus\tests\testmodel\User;
use taurus\tests\testmodel\WorkoutLocation;
use taurus\framework\api\SaveEntityApiController;
use taurus\framework\api\SaveEntityDefaultServiceImpl;
use taurus\framework\config\TaurusContainerConfig;
use taurus\framework\Container;
use taurus\framework\db\entity\BaseRepository;

use taurus\framework\mock\MockRequest;
use taurus\framework\mock\MockServer;
use taurus\tests\AbstractTaurusDatabaseTest;

class SaveEntityWithInputProcessorTest extends AbstractTaurusDatabaseTest
{
    /** @var SaveEntityApiController */
    private $controller;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        /** @var SaveEntityApiController $controller */
        $controller = Container::getInstance()->getService(TaurusContainerConfig::SERVICE_DEFAULT_SAVE_ENTITY_CONTROLLER);
        /** @var SaveEntityDefaultServiceImpl $service */
        $service = Container::getInstance()->getService(TaurusContainerConfig::SERVICE_DEFAULT_SAVE_ENTITY_SERVICE);
        $service->setEntityClass(User::class);
        $controller->setService($service);
        $this->controller = $controller;
    }

    /**
     * @return array
     */
    function getFixtureFiles(): array
    {
        return [
            'workout_location.xml',
            'muscle_group.xml',
            'exercise_group.xml',
            'exercise.xml',
            'user.xml'
        ];
    }

    public function testSaveEntityWithInputProcessor()
    {
        $mockRequest = (Container::getInstance()->getService(TaurusContainerConfig::SERVICE_MOCK_REQUEST))
            ->setMethod('POST')
            ->setUrl('/api/user')
            ->setInputBody([
                'user' => [
                    'username' => 'testuser',
                    'password' => 'test123'
                ]
            ])
            ->addHeader('x-token', $this->login()->getEncodedTokenString());

        $this->controller->handleRequest($mockRequest);

        /** @var MockServer $mockServer */
        $mockServer = Container::getInstance()->getService(TaurusContainerConfig::SERVICE_MOCK_SERVER);
        $actualResponse = json_decode($mockServer->get(
            '/api/user',
            'GET',
            ['id' => 3],
            [],
            ['x-token' => $this->login()->getEncodedTokenString()]
        ));

        $this->assertTrue(
            password_verify(
                'test123',
                $actualResponse->password
            )
        );
    }
}
